service: sentiment-service

functions:
  sentiment:
    timeout: 120
    description: comment sentiment analyzer
    handler: handler.sentiment
    events:
      - http:
          path: sentiment
          method: get
          cors: true

provider:
  name: aws
  timeout: 120
  runtime: python3.7

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
