service: numpy-test

functions:
  sentiment:
    description: new awesome function
    handler: handler.sentiment
    events:
      - http:
          path: sentiment
          method: get
          cors: true

provider:
  name: aws
  runtime: python3.8

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux